trigger:
  - master
  - dev/*

resources:
  repositories:
    - repository: pipelineTemplateRepository
      type: github
      name: emmanuelbenitez/BigSolution.Build.Agent.Yaml.Pipeline.Templates
      endpoint: github.com_emmanuelbenitez

variables:
  - template: version-variables.yml

extends:
  template: Pipelines/dotnet-nuget/continuous-integration.yml@pipelineTemplateRepository
  parameters:
    ProjectOrSolutionPath: "$(Build.SourcesDirectory)/Blazor.DynamicComponents.sln"