trigger: none

resources:
  repositories:
    - repository: pipelineTemplateRepository
      type: github
      name: emmanuelbenitez/BigSolution.Build.Agent.Yaml.Pipeline.Templates
      endpoint: github.com_emmanuelbenitez

extends:
  template: Pipelines/dotnet-nuget/release.yml@pipelineTemplateRepository
  parameters:
    ProjectOrSolutionPath: "$(Build.SourcesDirectory)/Blazor.DynamicComponents.sln"
    Major: ${{ variables.versionMajor }}
    Minor: ${{ variables.versionMinor }}
    Patch: ${{ variables.versionPatch }}
    PreRelease: