trigger:
  - master

resources:
  repositories:
    - repository: pipelineTemplateRepository
      type: github
      name: emmanuelbenitez/BigSolution.Build.Agent.Yaml.Pipeline.Templates
      endpoint: github.com_emmanuelbenitez

extends:
  template: Pipelines/dotnet-nuget/continuous-integration.yml@pipelineTemplateRepository
  parameters:
    ProjectOrSolutionPath: "$(Build.SourcesDirectory)/Blazor.DynamicComponents.sln"
    Major: 1
    Minor: 0